#!/usr/bin/env ruby

$LOAD_PATH.unshift 'lib'

require 'bundler'
Bundler.setup

require 'trello_jira_bridge'
require 'optparse'

options = {
  config: 'config/config.yml'
}
optparse = OptionParser.new do |opts|
  opts.on('-h','--help','Display this screen') do
    puts opts
    exit
  end
  opts.on('-c','--config FILENAME', 'Path to settings yamlfile. Default: config.yml') do |f|
    options[:config] = f
  end
end

optparse.parse!

TrelloJiraBridge.load_config(options[:config])

puts "updating data from JIRAs"
Bot.scan_trello_cards

