#!/usr/bin/env ruby

$LOAD_PATH.unshift 'lib'

require 'bundler'
Bundler.setup

require 'awesome_print'
require 'optparse'

# local libs
require 'trello_jira_bridge'

optparse = OptionParser.new do |opts|
  opts.on('-h','--help','Display this screen') do
    puts opts
    exit
  end
  opts.on('-c','--config FILENAME', 'Path to settings yamlfile. Default: config.yml') do |f|
    options[:config] = f
  end
end

optparse.parse!

TrelloJiraBridge.load_config(options[:config])

include Trello
include Trello::Authorization
Trello::Authorization.const_set :AuthPolicy, OAuthPolicy
OAuthPolicy.consumer_credential = OAuthCredential.new credentials[:public_key],credentials[:secret]
OAuthPolicy.token = OAuthCredential.new credentials[:key], nil

puts "updating data from JIRAs"
Bot.scan_trello_cards('jirabot')

